title: 'Emil Smith'
default_lang: en
author:
  name: Emil
  email: hi@emilsmith.pro
taxonomies:
  - category
  - tag
metadata:
  description: 'Emil Smith is a Digital Designer and Front End Developer from London, UK'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='